mqtt:
  - climate:
      name: "Alpicool fridge"
      unique_id: "alpicoolfriddgeuid"
      max_temp: 20
      min_temp: -20
      modes:
        - "off"
        - "cool"
      current_temperature_topic: "tele/zalpicool/sensor"
      current_temperature_template: "{{ value_json.f_actual_temperature | round(1, 'floor') }}"
      preset_modes:
        - "eco"
        - "burst"
      preset_mode_command_template: >-
        {% set jsonon = { 'fridge_eco': True } %}
        {% set jsonoff = { 'fridge_eco': False } %}
        {{ jsonon | tojson if value == 'eco' else jsonoff | tojson }}
      preset_mode_state_topic: "tele/zalpicool/sensor"
      preset_mode_value_template: >-
        {{ 'eco' if value_json.f_eco == True else 'burst' }}
      preset_mode_command_topic: "tele/zalpicool/cmd"
      mode_state_topic: "tele/zalpicool/sensor"
      mode_state_template: >-
        {{ 'cool' if value_json.f_on == True else 'off' }}
      mode_command_topic: "tele/zalpicool/cmd"
      mode_command_template: >-
        {% set jsonon = { 'fridge_on': True } %}
        {% set jsonoff = { 'fridge_on': False } %}
        {{ jsonon | tojson if value == 'cool' else jsonoff | tojson }}
      power_command_topic: "tele/zamovan-gps/cmd"
      payload_on: >
        { "fridge_on":true } "
      payload_off: >
        { "fridge_on":false } "
      temperature_command_topic: "tele/zalpicool/cmd"
      temperature_command_template: >
        {"fridge_temperature": {{ value }} }"
      temperature_state_topic: "tele/zalpicool/sensor"
      temperature_state_template: "{{ value_json.f_desired_temperature | round(1, 'floor')}}"
      temp_step: 1
      precision: 1
  - binary_sensor:
      name: "Fridge On"
      unique_id: zmkfridgeonoff
      state_topic: "tele/zalpicool/sensor"
      payload_on: true
      payload_off: false
      value_template: "{{ value_json.f_on }}"

  - binary_sensor:
      name: "Fridge Eco Mode"
      unique_id: zmkfridgeecomode
      state_topic: "tele/zalpicool/sensor"
      payload_on: true
      payload_off: false
      value_template: "{{ value_json.f_eco }}"

  - sensor:
      name: "Fridge Set Temperature"
      unique_id: zmkfridgessettemperature
      state_topic: "tele/zalpicool/sensor"
      suggested_display_precision: 0
      unit_of_measurement: "°C"
      value_template: "{{ value_json.f_desired_temperature }}"

  - sensor:
      name: "Fridge Temperature"
      unique_id: zmkfridgetemperature
      state_topic: "tele/zalpicool/sensor"
      suggested_display_precision: 0
      unit_of_measurement: "°C"
      value_template: "{{ value_json.f_actual_temperature }}"

  - sensor:
      name: "Fridge Voltage"
      unique_id: zmkfridgevoltage
      state_topic: "tele/zalpicool/sensor"
      suggested_display_precision: 2
      unit_of_measurement: "V"
      value_template: "{{ value_json.f_voltage | round(2, 'floor') }}"

  